#ifndef H_GLOBOX_WINDOWS
#define H_GLOBOX_WINDOWS

#include <stdint.h>
#include <stdbool.h>

#if defined(GLOBOX_CONTEXT_SOFTWARE)
	#include "software/globox_windows_software.h"
#elif defined(GLOBOX_CONTEXT_VULKAN)
	#include "vulkan/globox_windows_vulkan.h"
#elif defined(GLOBOX_CONTEXT_EGL)
	#include "egl/globox_windows_egl.h"
#elif defined(GLOBOX_CONTEXT_WGL)
	#include "wgl/globox_windows_wgl.h"
#endif

struct globox;

enum globox_windows_sizemove
{
	GLOBOX_WINDOWS_SIZEMOVE_WAITMODAL = 0, // waiting for the modal loop
	GLOBOX_WINDOWS_SIZEMOVE_WAITEDGES,     // waiting for the edge info
	GLOBOX_WINDOWS_SIZEMOVE_KILLMODAL,     // killing the modal loop
	GLOBOX_WINDOWS_SIZEMOVE_SYNTHDRAG,     // synthetizing a mouse drag
	GLOBOX_WINDOWS_SIZEMOVE_STARTSIZE,     // starting the resize
};

struct globox_platform
{
	HWND globox_platform_event_handle;
	uint32_t* globox_platform_argb;

#if defined(GLOBOX_CONTEXT_SOFTWARE)
	struct globox_windows_software globox_windows_software;
#elif defined(GLOBOX_CONTEXT_VULKAN)
	struct globox_windows_vulkan globox_windows_vulkan;
#elif defined(GLOBOX_CONTEXT_EGL)
	struct globox_windows_egl globox_windows_egl;
#elif defined(GLOBOX_CONTEXT_WGL)
	struct globox_windows_wgl globox_windows_wgl;
#endif

	MSG globox_windows_msg;
	LPWSTR globox_windows_wide_title;
	LPWSTR globox_windows_class_name;
	HMODULE globox_windows_class_module_handle;
	WNDCLASSEX globox_windows_class;

	LONG globox_windows_style_backup;
	LONG globox_windows_exstyle_backup;
	WINDOWPLACEMENT globox_windows_position_backup;

	uint32_t globox_windows_old_outer_x;
	uint32_t globox_windows_old_outer_y;
	uint32_t globox_windows_framediff_x;
	uint32_t globox_windows_framediff_y;

	uint32_t globox_windows_outer_width;
	uint32_t globox_windows_outer_height;
	uint32_t globox_windows_old_outer_width;
	uint32_t globox_windows_old_outer_height;

	int64_t globox_windows_interactive_x;
	int64_t globox_windows_interactive_y;
	enum globox_windows_sizemove globox_windows_sizemove_step;

	void (*globox_windows_resize_callback)(struct globox* globox);
	void (*globox_windows_dcomp_callback)(struct globox* globox);
	void (*globox_windows_dwm_transparency_callback)(struct globox* globox);
};

enum globox_error
{
	// special error code to signal everything is fine
	GLOBOX_ERROR_OK = 0,

	// error codes describing the nature of the problem
	GLOBOX_ERROR_NULL,
	GLOBOX_ERROR_ALLOC,
	GLOBOX_ERROR_BOUNDS,
	GLOBOX_ERROR_DOMAIN,

	// extra high-level error codes for use by the developer
	// they can be used to throw a more generic error and
	// describe the context instead of the error itself
	GLOBOX_ERROR_FUNC_OPEN,
	GLOBOX_ERROR_FUNC_CLOSE,

	GLOBOX_ERROR_FUNC_PLATFORM_INIT,
	GLOBOX_ERROR_FUNC_PLATFORM_FREE,
	GLOBOX_ERROR_FUNC_PLATFORM_CREATE_WINDOW,
	GLOBOX_ERROR_FUNC_PLATFORM_HOOKS,
	GLOBOX_ERROR_FUNC_PLATFORM_COMMIT,
	GLOBOX_ERROR_FUNC_PLATFORM_PREPOLL,
	GLOBOX_ERROR_FUNC_PLATFORM_EVENTS_POLL,
	GLOBOX_ERROR_FUNC_PLATFORM_EVENTS_WAIT,
	GLOBOX_ERROR_FUNC_PLATFORM_EVENTS_HANDLE,
	GLOBOX_ERROR_FUNC_PLATFORM_SET_ICON,
	GLOBOX_ERROR_FUNC_PLATFORM_SET_TITLE,
	GLOBOX_ERROR_FUNC_PLATFORM_SET_STATE,

	GLOBOX_ERROR_FUNC_SOFTWARE_INIT,
	GLOBOX_ERROR_FUNC_SOFTWARE_FREE,
	GLOBOX_ERROR_FUNC_SOFTWARE_CREATE,
	GLOBOX_ERROR_FUNC_SOFTWARE_SHRINK,
	GLOBOX_ERROR_FUNC_SOFTWARE_RESERVE,
	GLOBOX_ERROR_FUNC_SOFTWARE_EXPOSE,
	GLOBOX_ERROR_FUNC_SOFTWARE_COPY,

	// platform errors
	GLOBOX_ERROR_WINDOWS_SYM,
	GLOBOX_ERROR_WINDOWS_MODULE_APP,
	GLOBOX_ERROR_WINDOWS_MODULE_USER32,

	GLOBOX_ERROR_WINDOWS_DELETE,
	GLOBOX_ERROR_WINDOWS_DEVICE_CONTEXT_GET,

	GLOBOX_ERROR_WINDOWS_MESSAGE_GET,
	GLOBOX_ERROR_WINDOWS_CLASS_REGISTER,

	GLOBOX_ERROR_WINDOWS_WINDOW_CREATE,
	GLOBOX_ERROR_WINDOWS_WINDOW_ADJUST,
	GLOBOX_ERROR_WINDOWS_WINDOW_UPDATE,
	GLOBOX_ERROR_WINDOWS_WINDOW_RECT_GET,
	GLOBOX_ERROR_WINDOWS_WINDOW_POS_SET,

	GLOBOX_ERROR_WINDOWS_WINDOW_LONG_GET,
	GLOBOX_ERROR_WINDOWS_WINDOW_LONG_SET,
	GLOBOX_ERROR_WINDOWS_PLACEMENT_GET,
	GLOBOX_ERROR_WINDOWS_PLACEMENT_SET,

	GLOBOX_ERROR_WINDOWS_CLIENT_RECT,
	GLOBOX_ERROR_WINDOWS_CLIENT_POS,

	GLOBOX_ERROR_WINDOWS_TRANSPARENCY_REGION,
	GLOBOX_ERROR_WINDOWS_TRANSPARENCY_DWM,
	GLOBOX_ERROR_WINDOWS_COMP_ATTR,

	GLOBOX_ERROR_WINDOWS_INPUT_SEND,
	GLOBOX_ERROR_WINDOWS_CAPTURE_RELEASE,

	GLOBOX_ERROR_WINDOWS_CURSOR_LOAD,
	GLOBOX_ERROR_WINDOWS_CURSOR_POS_GET,
	GLOBOX_ERROR_WINDOWS_CURSOR_POS_SET,

	GLOBOX_ERROR_WINDOWS_BMP_MASK_CREATE,
	GLOBOX_ERROR_WINDOWS_BMP_COLOR_CREATE,

	GLOBOX_ERROR_WINDOWS_ICON_CREATE,
	GLOBOX_ERROR_WINDOWS_ICON_SMALL,
	GLOBOX_ERROR_WINDOWS_ICON_BIG,

	GLOBOX_ERROR_WINDOWS_UTF8,
	GLOBOX_ERROR_WINDOWS_TITLE,

	// gdi
	GLOBOX_ERROR_WINDOWS_GDI_DAMAGE,
	GLOBOX_ERROR_WINDOWS_GDI_PAINT,
	GLOBOX_ERROR_WINDOWS_GDI_BITBLT,
	GLOBOX_ERROR_WINDOWS_GDI_DIB_CREATE,
	GLOBOX_ERROR_WINDOWS_GDI_BITMAP_SELECT,
	GLOBOX_ERROR_WINDOWS_GDI_DEVICE_CONTEXT_CREATE,
	GLOBOX_ERROR_WINDOWS_GDI_DEVICE_CONTEXT_DELETE,

	// egl
	GLOBOX_ERROR_WINDOWS_EGL_INIT,
	GLOBOX_ERROR_WINDOWS_EGL_API_BIND,
	GLOBOX_ERROR_WINDOWS_EGL_DISPLAY_GET,
	GLOBOX_ERROR_WINDOWS_EGL_CONFIG_CHOOSE,
	GLOBOX_ERROR_WINDOWS_EGL_CONFIG_ATTRIB_GET,
	GLOBOX_ERROR_WINDOWS_EGL_CONTEXT_CREATE,
	GLOBOX_ERROR_WINDOWS_EGL_CONTEXT_DESTROY,
	GLOBOX_ERROR_WINDOWS_EGL_SURFACE_CREATE,
	GLOBOX_ERROR_WINDOWS_EGL_SURFACE_DESTROY,
	GLOBOX_ERROR_WINDOWS_EGL_MAKE_CURRENT,
	GLOBOX_ERROR_WINDOWS_EGL_TERMINATE,
	GLOBOX_ERROR_WINDOWS_EGL_SWAP,

	// wgl
	GLOBOX_ERROR_WINDOWS_WGL_PIXEL_FORMAT_CHOOSE,
	GLOBOX_ERROR_WINDOWS_WGL_PIXEL_FORMAT_SET,
	GLOBOX_ERROR_WINDOWS_WGL_CONTEXT_CREATE,
	GLOBOX_ERROR_WINDOWS_WGL_CONTEXT_DELETE,
	GLOBOX_ERROR_WINDOWS_WGL_CONTEXT_SET,
	GLOBOX_ERROR_WINDOWS_WGL_SWAP,

	// special value used to get the total number of error codes
	GLOBOX_ERROR_SIZE,
};

#endif
