#ifndef H_GLOBOX_X11_HELPERS
#define H_GLOBOX_X11_HELPERS

enum x11_atom_types
{
	ATOM_STATE_MAXIMIZED_HORZ = 0,
	ATOM_STATE_MAXIMIZED_VERT,
	ATOM_STATE_FULLSCREEN,
	ATOM_STATE_HIDDEN,
	ATOM_STATE,
	ATOM_ICON,
	ATOM_PROTOCOLS,
	ATOM_DELETE_WINDOW,
	ATOM_COUNT // used to get size
};

#endif
